In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
df1 = pd.read_csv("corridor.csv",sep =";")
df1["location"] = 601*[1]
df1 = df1.drop(["Unnamed: 5"],axis=1)
df1.to_csv("corridor.csv",sep=";")
df1.head()

freq[Hz]  re:Trc1_S11  im:Trc1_S11  re:Trc2_S21  im:Trc2_S21  location
0  2.400000e+09     0.150847     0.112573     0.000150    -0.003453         1
1  2.400167e+09     0.150640     0.110470     0.000107    -0.003357         1
2  2.400333e+09     0.151034     0.108374     0.000086    -0.003420         1
3  2.400500e+09     0.151127     0.105698     0.000075    -0.003568         1
4  2.400667e+09     0.151428     0.103363    -0.000033    -0.003591         1

In [14]:
df2 = pd.read_csv("hall.csv",sep =";")

# df2["location"] = 601*[2]
# df2.to_csv("hall.csv",sep=";")
df2.head()

Unnamed: 0      freq[Hz]  re:Trc1_S11  im:Trc1_S11  re:Trc2_S21  \
0           0  2.400000e+09     0.169901     0.039112     0.001952   
1           1  2.400167e+09     0.170837     0.038595     0.001978   
2           2  2.400333e+09     0.171450     0.037803     0.001985   
3           3  2.400500e+09     0.172002     0.037207     0.002133   
4           4  2.400667e+09     0.172383     0.036402     0.002282   

   im:Trc2_S21  location  
0     0.000174         2  
1     0.000449         2  
2     0.000433         2  
3     0.000507         2  
4     0.000509         2

In [15]:
df3 = pd.read_csv("lab.csv",sep =";")
# df3 = df3.drop(["Unnamed: 5"],axis=1)
# df3["location"] = 601*[3]
df3.head()
# df3.to_csv("lab.csv",sep=";")

Unnamed: 0      freq[Hz]  re:Trc1_S11  im:Trc1_S11  re:Trc2_S21  \
0           0  2.400000e+09     0.157296     0.062804     0.000503   
1           1  2.400167e+09     0.157362     0.061130     0.000863   
2           2  2.400333e+09     0.157071     0.059171     0.000844   
3           3  2.400500e+09     0.157248     0.057201     0.001086   
4           4  2.400667e+09     0.157024     0.055298     0.001171   

   im:Trc2_S21  location  
0     0.004841         3  
1     0.004674         3  
2     0.004678         3  
3     0.004684         3  
4     0.004756         3

In [16]:
df4 = pd.read_csv("lobby.csv",sep =";")
# df4 = df4.drop(["Unnamed: 0.1"],axis=1)
# df4 = df4.drop(["Unnamed: 0"],axis=1)


# df4["location"] = 601*[4]

# df4.to_csv("lobby.csv",sep=";")
df4.head()



Unnamed: 0      freq[Hz]  re:Trc1_S11  im:Trc1_S11  re:Trc2_S21  \
0           0  2.400000e+09     0.169438     0.045991    -0.004257   
1           1  2.400167e+09     0.170521     0.044999    -0.004037   
2           2  2.400333e+09     0.171259     0.043860    -0.004080   
3           3  2.400500e+09     0.172326     0.042828    -0.004060   
4           4  2.400667e+09     0.173289     0.041912    -0.004082   

   im:Trc2_S21  location  
0    -0.000210         4  
1    -0.000066         4  
2     0.000180         4  
3     0.000240         4  
4     0.000581         4

In [46]:
# df = pd.DataFrame()
# for file in os.listdir(os.getcwd()):
#     if file.endswith('.csv'):
#         df = df.append(pd.read_csv(file,sep=';'))

# df = pd.read_csv("combined.csv",sep=";")
# df.to_csv("combined.csv",sep=";")
df = pd.read_csv("combined.csv",sep=";")
df = df.drop(["Unnamed: 0"],axis=1)
# df = df.drop(["Unnamed: 0.1"],axis=1)
# 
# from sklearn.utils import shuffle
# df = shuffle(df)
# df.to_csv("combined.csv",sep=";")   
print(df.head())
# print(df.info())

       freq[Hz]  re:Trc1_S11  im:Trc1_S11  re:Trc2_S21  im:Trc2_S21  location
0  2.442500e+09     0.065093    -0.178887     0.002500     0.000091         3
1  2.495000e+09    -0.167017     0.018190    -0.000653     0.002994         2
2  2.404333e+09     0.176713     0.053134    -0.002797    -0.001517         1
3  2.461167e+09    -0.030018    -0.180157    -0.000755    -0.002616         4
4  2.494500e+09    -0.180017     0.009182    -0.001318    -0.000188         3


In [50]:
x = df.iloc[:,1:-1].values
y = df.iloc[:,5].values
print(y)
print(x)


[3 2 1 ... 4 3 1]
[[ 6.50930852e-02 -1.78887486e-01  2.49989424e-03  9.14723787e-05]
 [-1.67016670e-01  1.81901362e-02 -6.52966730e-04  2.99406005e-03]
 [ 1.76713213e-01  5.31339012e-02 -2.79671303e-03 -1.51681330e-03]
 ...
 [ 3.19809131e-02 -1.72506765e-01  4.42481926e-03  3.60294973e-04]
 [ 1.65817484e-01  2.53259186e-02  4.07670625e-03  3.09458328e-03]
 [ 9.25502107e-02 -1.58348009e-01 -1.22473214e-03 -1.03796681e-03]]


In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [52]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(X_train)
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [54]:
y_pred = classifier.predict(X_test)

In [60]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       117
           2       1.00      1.00      1.00       121
           3       1.00      1.00      1.00       116
           4       1.00      1.00      1.00       127

    accuracy                           1.00       481
   macro avg       1.00      1.00      1.00       481
weighted avg       1.00      1.00      1.00       481



In [59]:
classifier.predict(X_train[0])

ValueError: Expected 2D array, got 1D array instead:
array=[-1.44457528  0.38697654 -0.14420364 -0.89942267].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.